import pandas as pd

file_path = '/Users/songyafeng/6.2/CFL/Assignment/AI-generated-text-detection/processed_data.csv'

df = pd.read_csv(file_path)
# Add a new column 'gpt4' to store the answers generated by GPT-4
df['gpt4'] = ''

# Selecting the first 499 rows
df_subset = df.iloc[1:500]

# Save the pruned file
subset_file_path = '/Users/songyafeng/6.2/CFL/Assignment/AI-generated-text-detection/pruned_data.csv'
df_subset.to_csv(subset_file_path, encoding='utf-8', index=False)

print("shape", df_subset.shape)

for index, row in df_subset.iterrows():
    question = ("Generate a Quora-like answer based on the question \""
                + row['question']
                + "\" with referring to the answer \""
                + row['answer']
                + "\" and start the answer with the first 8 words of the reference answer."
                  "The generated answer should have similar word amount of the reference answer.")
    print(question)